### ISSUE TITLE
questions about awf and wf in model

### ISSUE THREAD

**Issue by nicolechenbiiiii** [Liuxyu/DF#1]
Hi, thanks for the implementation of deep fingerprinting in Pytorch, the code you wrote is very concise!

Since you didn't add any comments in code, so could you tell me about what is AWF and WF in model? Cause they don't look like Model_WTFPAD or Model_WalkieTalkie.

Thanks for your work again!
Looking forward to your reply.

**Comment by liuxyu** [comment]
AWF is from the paper https://arxiv.org/abs/1708.06376 which stands for Automated Website Fingerprinting.
WF is the original shallow model for Website Fingerprinting.

**Comment by nicolechenbiiiii** [comment]
> AWF is from the paper https://arxiv.org/abs/1708.06376 which stands for Automated Website Fingerprinting. WF is the original shallow model for Website Fingerprinting.

thx!
So another question arises, the data you shared is generated from the data of deepfingerprinting?

**Comment by liuxyu** [comment]
> 

You can find the dataset from https://distrinet.cs.kuleuven.be/software/tor-wf-dl/
